### ISSUE TITLE
Pagination error on admin screen

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKhub-Content-Drupal#1]
On installing, enabling module and entering API key on OKHUB API Module settings page:

Notice: Undefined variable: next_page in OkhubApiWrapper->makeRequest() (line 345 of ../modules/okhubapi/okhubwrapper/okhubwrapper.wrapper.inc).
Notice: Undefined variable: prev_page in OkhubApiWrapper->makeRequest() (line 345 of ../modules/okhubapi/okhubwrapper/okhubwrapper.wrapper.inc).
Notice: Undefined variable: next_page in OkhubApiWrapper->makeRequest() (line 351 of ../modules/okhubapi/okhubwrapper/okhubwrapper.wrapper.inc).
Notice: Undefined variable: prev_page in OkhubApiWrapper->makeRequest() (line 351 of ../modules/okhubapi/okhubwrapper/okhubwrapper.wrapper.inc).

(Can be replicated by just going to the OKHUB API Module settings page)

**Comment by joe-mcpherson** [comment]
Fixed. Actually in wrapper code. Retested in Widget.
