### ISSUE TITLE
Reorganise admin/settings screens

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKhub-Content-Drupal#14]
Reorganise settings screens - Aim to make it simple for a basic user but still be able to show the granular functionality for the advanced use cases.
Poss using tabs with basic and advanced sections
Could be named: Global settings/Themes/Countries/Manual import - the latter 3 only available if Import module enabled.

Needs discussion and specification

**Comment by joe-mcpherson** [comment]
Done with collapsible fieldsets (as per Peter's recommendation). I think this works a lot better. I'll close this issue for now and then if we want to rework the UX we can reopen or open a new issue with notes from that further discussion and specification
