### ISSUE TITLE
Taxonomy import error

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKhub-Content-Drupal#2]
Theme import fails "Term name missing" - poss looking for "name" attribute rather than "title" e.g. Eldis works http://api.okhub.org/v1/hub/search/themes/full/?source=eldis but SERPP doesn't http://api.okhub.org/v1/hub/search/themes/full/?source=serpp

**Comment by joe-mcpherson** [comment]
Fixed - this is because the Feeds Importer was looking for "name" in the API, which worked for Eldis, Bridge but not other sources. Now looks for "title".
