### ISSUE TITLE
Give descriptions for data sources

### ISSUE THREAD

**Issue by simoncolmer** [oriel-hub/OKhub-Content-Drupal#3]
For Default data sources (OKHUB API Module settings) - would be good to show descriptions of the data sources to explain the acronyms to the user - hover over/text to the right of the labels? 

Logo too?

(think this info is available via the API http://api.okhub.org/v1/hub/search/sources/full?q=eldis)

**Comment by joe-mcpherson** [comment]
Now show's details on mouse over of source options(see on demo site http://drupal.dev.ids.ac.uk/admin/config/services/okhubapi)

Required change in wrapper too:
https://github.com/oriel-hub/OKHub-php-Wrapper/commit/bea3be11f187701bb87ec86932e62ca6e24387d2
